# Generated by Django 3.0.7 on 2020-06-10 03:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('message_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(blank=True, default='', max_length=100)),
                ('event', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('track', 'track'), ('screen', 'screen'), ('page', 'page'), ('identity', 'identity')], default='track', max_length=25)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField()),
                ('context', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
