# Generated by Django 3.0.7 on 2020-06-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200611_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='originalTimestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='receivedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='sentAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
